import Head from 'next/head';
import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
// import LandingLayout from "@/components/layouts";

const inter = Inter({ subsets: ["latin"],  });

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-cinzel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Head>
        <link rel="icon" href="./icon.png" />
      </Head>
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
